version: '3'

services:
  db:
    container_name: db-star
    image: mongo:star
    build: ./db
    restart: always
    # ports:
    #   - "127.0.0.1:27017:27017"
    # network_mode: "host"
    volumes:
      - './db/data/:/data/db/'
  
  redis:
    container_name: redis-star
    image: redis:star
    build: ./redis
    restart: always
    command: redis-server --appendonly yes
    # ports:
    #   - "127.0.0.1:6379:6379"
    # network_mode: "host"
    volumes:
      - ./redis/data:/data

  web:
    container_name: web-star
    image: web:star
    build: ./web
    restart: always
    command: sh -c "/run.sh"
    # network_mode: "host"
    volumes:
      - './web/run.sh:/run.sh'
      - './web/crontab:/crontab'
      - './web/supervisord.conf:/etc/supervisord.conf'
      - './web/app:/www'
      - '/tmp/key:/tmp/key'
      - '/media/data:/media/data'
    depends_on:
      - db
      - redis
  
  nginx:
    container_name: nginx-star
    image: nginx:star
    build: ./nginx
    restart: always
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
      - "62400:62400"
      # - "127.0.0.1:62401:62401"
      # - "127.0.0.1:1935:1935"
    # network_mode: "host"
    volumes:
      # - './nginx/nginx_init.conf:/opt/nginx/nginx.conf'
      - './nginx/nginx.conf:/opt/nginx/nginx.conf'
      - './web/app:/www'
      - '/tmp/key:/tmp/key'
      - '/media/data:/media/data'
      - '/etc/letsencrypt:/etc/letsencrypt'
      - './letsencrypt/letsencrypt-www:/tmp/letsencrypt'
    depends_on:
      - web
  
  letsencrypt:
    container_name: letsencrypt-star
    restart: always
    build: ./letsencrypt
    image: letsencrypt:star
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/letsencrypt:/etc/letsencrypt
      - './letsencrypt/letsencrypt-www:/tmp/letsencrypt'
    environment:
      LE_RENEW_ID: nginx-star  # nginx's container name
      DOMAINS: ssl.itlab.ee.ncku.edu.tw
      EMAIL: ddl.itlab@gmail.com
      WEBROOT_PATH: /tmp/letsencrypt
      EXP_LIMIT: 30
      CHECK_FREQ: 30
    depends_on:
      - nginx

  sshd:
    container_name: sshd-star
    image: sshd:star
    build: ./sshd
    restart: always
    command: sh -c "/run.sh"
    ports:
      - "62422:62422"
    # network_mode: "host"
    volumes:
      - './sshd/host_keys:/host_keys'
      - './sshd/authorized_keys:/home/limited-user/.ssh/authorized_keys'
    depends_on:
      - web
      - nginx
