version: '3'

services:
  db:
    container_name: db-star
    image: mongo:star
    build: ./db
    restart: always
    volumes:
      - './db/data/:/data/db/'
  
  redis:
    container_name: redis-star
    image: redis:star
    build: ./redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./redis/data:/data

  web:
    container_name: web-star
    image: web:star
    build: ./web
    restart: always
    command: sh -c "/run.sh"
    volumes:      
      - './web/app:/www'
      - './web/supervisord.conf:/supervisord.conf'
      - './web/logrotate.conf:/logrotate.conf'
      - './web/crontab:/crontab'
      - './web/run.sh:/run.sh'
      - './sshd/authorized_keys:/authorized_keys'
      - './log/web/:/var/log/'
      - '/media/data/record:/media/data/record'
    depends_on:
      - db
      - redis
  
  nginx:
    container_name: nginx-star
    image: nginx:star
    build: ./nginx
    restart: always
    command: sh -c "/run.sh"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - './nginx/nginx_init.conf:/opt/nginx/nginx.conf'
      - './nginx/nginx.conf:/opt/nginx/nginx.conf'
      - './nginx/logrotate.conf:/logrotate.conf'
      - './nginx/crontab:/crontab'
      - './nginx/run.sh:/run.sh'
      - './web/app:/www'
      - './letsencrypt/letsencrypt-www:/tmp/letsencrypt'
      - './log/nginx/:/opt/nginx/logs/'
      - '/tmp/key:/tmp/key'
      - '/media/data/record:/media/data/record'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - web
  
  letsencrypt:
    container_name: letsencrypt-star
    restart: always
    build: ./letsencrypt
    image: letsencrypt:star
    volumes:
      - './letsencrypt/letsencrypt-www:/tmp/letsencrypt'
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LE_RENEW_ID: nginx-star  # nginx's container name
      DOMAINS: ssl.itlab.ee.ncku.edu.tw
      EMAIL: ddl.itlab@gmail.com
      WEBROOT_PATH: /tmp/letsencrypt
      EXP_LIMIT: 30
      CHECK_FREQ: 30
    depends_on:
      - nginx

  sshd:
    container_name: sshd-star
    image: sshd:star
    build: ./sshd
    restart: always
    command: sh -c "/run.sh"
    ports:
      - "62422:62422"
    volumes:
      - './sshd/host_keys:/host_keys'
      - './sshd/authorized_keys:/home/limited-user/.ssh/authorized_keys'
    depends_on:
      - web
      - nginx
