version: '3'

services:
  db:
    container_name: db-star
    image: alpine-mongo:star
    build: ./db
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - './db/data/:/data/db/'
  
  redis:
    container_name: redis-star
    image: alpine-redis:star
    build: ./redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis/data:/data

  web:
    container_name: web-star
    image: web:star
    build: ./web
    restart: always
    command: sh -c "/run.sh"
    volumes:
      - './web/run.sh:/run.sh'
      - './web/crontab:/crontab'
      - './web/supervisord.conf:/etc/supervisord.conf'
      - './web/app:/www'
      - '/tmp/key:/tmp/key'
      - '/media/data:/media/data'
    depends_on:
      - db
      - redis
  
  nginx:
    container_name: nginx-star
    image: nginx:star
    build: ./nginx
    restart: always
    command: nginx -g 'daemon off;'
    ports:
      - "62400:62400"
      - "127.0.0.1:62401:62401"
      - "1935:1935"
    volumes:
      - '/etc/dehydrated/certs/ssl.itlab.ee.ncku.edu.tw/privkey.pem:/opt/nginx/privkey.pem'
      - '/etc/dehydrated/certs/ssl.itlab.ee.ncku.edu.tw/fullchain.pem:/opt/nginx/fullchain.pem'
      - './nginx/nginx.conf:/opt/nginx/nginx.conf'
      - './web/app:/www'
      - '/tmp/key:/tmp/key'
      - '/media/data:/media/data'
    depends_on:
      - web
