# Generated by Django 2.1.7 on 2019-03-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tx2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantinfo',
            name='device',
        ),
        migrations.DeleteModel(
            name='InstantInfo',
        ),
    ]
