# Generated by Django 2.1.5 on 2019-01-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tx2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinfonow',
            old_name='device_name',
            new_name='device',
        ),
        migrations.AlterField(
            model_name='deviceinfonow',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
