version: '3'

networks:
  docker_host:
    external:
      name: 'host'

services:
  
  visualizer:
    image: dockersamples/visualizer:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "50000:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 30s
      placement:
        constraints: [node.role == manager]
  
  live555proxy:
    image: migoller/live555proxyserverdocker:latest
    command:
      - -v
      - |
        ${RTSP_URI}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "50001:554"
      # - "50002:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 30s
      placement:
        constraints: [node.role == manager]