# Generated by Django 2.1.5 on 2019-01-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('longitude', models.FloatField(default=120.224)),
                ('latitude', models.FloatField(default=22.996)),
                ('uri', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
