# Generated by Django 2.1.5 on 2019-01-22 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('longitude', models.FloatField(default=120.22283)),
                ('latitude', models.FloatField(default=22.99672)),
                ('uri', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('pm2_5', models.FloatField(default=0.0)),
                ('loudness', models.FloatField(default=0.0)),
                ('light_intensity', models.FloatField(default=0.0)),
                ('uv_intensity', models.FloatField(default=0.0)),
                ('ir_sensed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_history', to='home.Device')),
            ],
        ),
    ]
