# Generated by Django 2.1.5 on 2019-01-28 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
