# Generated by Django 2.2.1 on 2019-05-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190330_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.SlugField(max_length=20, primary_key=True, serialize=False, verbose_name='Device ID (uneditable)'),
        ),
    ]
