# Generated by Django 2.2.2 on 2019-06-07 15:32

from django.db import migrations
import djongo.models.json


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190607_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='pir_schedule',
            field=djongo.models.json.JSONField(default=[{'day': 0, 'periods': []}, {'day': 1, 'periods': []}, {'day': 2, 'periods': []}, {'day': 3, 'periods': []}, {'day': 4, 'periods': []}, {'day': 5, 'periods': []}, {'day': 6, 'periods': []}]),
        ),
    ]
