# Generated by Django 2.1.5 on 2019-01-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ssh_pub',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='SSH Public Key'),
        ),
    ]
