# Generated by Django 2.2.1 on 2019-05-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190513_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.SlugField(max_length=20, primary_key=True, serialize=False, verbose_name='Device ID (unmodifiable)'),
        ),
    ]
