# Generated by Django 2.2.2 on 2019-06-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_device_pir_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ssh_pub',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='ssh-rsa [key] [comment]'),
        ),
    ]
