# Generated by Django 2.1.7 on 2019-03-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190128_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ssh_pub',
            field=models.CharField(blank=True, default='ssh-rsa [key] [device_name]', max_length=1000, verbose_name='SSH Public Key'),
        ),
    ]
