# Generated by Django 2.1.7 on 2019-03-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190308_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ssh_pub',
            field=models.CharField(blank=True, default='ssh-rsa [key] [comment]', max_length=1000, verbose_name='SSH Public Key'),
        ),
    ]
