# Generated by Django 2.2.1 on 2019-06-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190513_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyinfo',
            old_name='ir_sensed',
            new_name='led_status',
        ),
    ]
